import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import Navbarre from './Component/Navbarre';
import Footer from './Component/Footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="icon" href="" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="" />
        <link rel="apple-touch-icon" href="" /> 
        <link rel="manifest" href="" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
        <title>Planify</title>
      </head>
      <body className="">
        <Navbarre />
        <div className='pt-28 permax1:pt-10  w-full'>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
